### ISSUE TITLE
Support more platforms

### ISSUE THREAD

**Issue by hawkins** [Chris-Perkins/SwiftTwitch#2]
Hey, great job with the library!

I'm hoping to use it in TvOS, but I was greeted with this error when trying to install the pod:

```
$ pod install
Analyzing dependencies
[!] The platform of the target `my-project-here` (tvOS 13.0) is not compatible with `SwiftTwitch (0.1.0)`, which does not support `tvOS`.
```

Is there any particular reason this library doesn't support more platforms like MacOS, TvOS? I'd be happy to help port for support if needed, but I've never used Cocoapods before so I'm not sure where to look to see why it doesn't already work for more than iOS.

**Comment by hawkins** [comment]
... I was able to at least preliminarily install it by making [this change](https://github.com/hawkins/SwiftTwitch/commit/3df69d7e2c2da1d1a379ae2baf7d8d16c9ab8266), but who knows what if anything will break. I'll hopefully report back if my novice swift skills can manage to keep marching. PR will be incoming if it works 🤞

**Comment by Chris-Perkins** [comment]
Hi Hawkins, thanks for the kind words! I didn't include tvOS/macOS support as I didn't test the platform with them, but the library should work on them. It'd be awesome if you came back with any findings/that PR! Thanks for using the library :)
